rbac:
  create: true

controller:
  kind: DaemonSet
  service:
    type: NodePort
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-preemptible
            operator: NotIn
            values:
              - "true"
  daemonset:
    useHostPort: "true"
  defaultBackendService: kube-system/default-http-backend
  stats:
    enabled: true
  metrics:
    enabled: true
  config:
    hsts-include-subdomains: "false"
#    enable-opentracing: true
#    zipkin-collector-host: zipkin-collector

defaultBackend:
  enabled: "false"
